Laba 1
Illia-M/TRPZ-git pull request #227
Opened 2024-02-13 09:58 UTC by art3mk405

2024-02-13 10:00 UTC, romkas228 approved these changes

2024-02-13 10:02 UTC, bohdan-kov approved these changes

2024-02-13 10:52 UTC, olddyy approved these changes

2024-02-13 11:43 UTC, Illia-M approved these changes

2024-02-13 11:43 UTC, Illia-M commented on GitPractice.Domain/StudentsProvider.cs
> +                { new GroupNumber("IC-31"), new[]{new Student("Artem", "Voloshyn") }.ToImmutableList() },
Add new student to group and leave all already added students

2024-02-13 11:43 UTC, Illia-M requested changes
Missclick

2024-02-14 07:07 UTC, AlexanderSychev2005 approved these changes

2024-02-15 10:22 UTC, closed without merging