student data changed
Illia-M/TRPZ-git pull request #229
Opened 2024-02-13 09:59 UTC by hanbaori

2024-02-13 10:14 UTC, longvodyneste approved these changes, later dismissed
ttchoppa

2024-02-13 10:18 UTC, bohdan-kov submitted a review, later dismissed

2024-02-13 10:28 UTC, DeZPeR1 submitted a review, later dismissed

2024-02-13 11:44 UTC, Illia-M requested changes

2024-02-13 11:44 UTC, Illia-M commented on GitPractice.sln
> +VisualStudioVersion = 17.7.34031.279
Do not change csproj\sln files

2024-02-13 12:03 UTC, hanbaori commented on GitPractice.sln
> +VisualStudioVersion = 17.7.34031.279
Changed it to the original one. It was changed not on purpose (due to reintsallation of Visual Studio)

2024-02-13 19:09 UTC, AlexanderSychev2005 approved these changes

2024-02-14 07:09 UTC, AlexanderSychev2005 approved these changes

2024-02-14 07:41 UTC, closed without merging