Laba1
Illia-M/TRPZ-git pull request #236
Opened 2024-02-13 10:48 UTC by olddyy

2024-02-13 10:50 UTC, bohdan-kov approved these changes, later dismissed

2024-02-13 11:34 UTC, longvodyneste approved these changes, later dismissed

2024-02-13 11:47 UTC, Illia-M requested changes

2024-02-13 11:47 UTC, Illia-M commented on GitPractice.Domain/GitPractice.csproj
> -
Do not change csproj/sln files

2024-02-13 11:47 UTC, Illia-M commented on GitPractice.Domain/StudentsProvider.cs
> +                { new GroupNumber("IC-31"), new[]{new Student("Dmytro", "Belousov") }.ToImmutableList() },
Add new student to list and leave all added previously

2024-02-13 22:36 UTC, sayonararose submitted a review, later dismissed

2024-02-15 13:17 UTC, bohdan-kov approved these changes

2024-02-15 13:19 UTC, closed without merging